version: '3.1'

services:
  www-wstudio:
    container_name: www-wstudio
    image: www-wstudio
    build: .
    ports:
      - "3200:3000"
    networks:
      - homedock

networks:
  homedock:
    external: true
