version: '3.1'

services:
  watershedstudio:
    container_name: watershedstudio
    image: watershed.studio:www
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:3000"
    networks:
      - homedock

networks:
  homedock:
    external: true
